//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalPortfolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class AdminLoginTbl
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<long> Role { get; set; }
        public Nullable<long> IsActive { get; set; }
    }
}
