//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalPortfolio
{
    using System;
    using System.Collections.Generic;
    
    public partial class GalleryTbl
    {
        public long Id { get; set; }
        public Nullable<long> AlbumID { get; set; }
        public string ImagePath { get; set; }
        public Nullable<long> IsActive { get; set; }
    
        public virtual AlbumTbl AlbumTbl { get; set; }
    }
}
