//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PoliticalPortfolio
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PoliticalDBEntities : DbContext
    {
        public PoliticalDBEntities()
            : base("name=PoliticalDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLoginTbl> AdminLoginTbls { get; set; }
        public virtual DbSet<AlbumTbl> AlbumTbls { get; set; }
        public virtual DbSet<ContactUsTbl> ContactUsTbls { get; set; }
        public virtual DbSet<GalleryTbl> GalleryTbls { get; set; }
        public virtual DbSet<SliderTbl> SliderTbls { get; set; }
        public virtual DbSet<VideoTbl> VideoTbls { get; set; }
        public virtual DbSet<EventTbl> EventTbls { get; set; }
        public virtual DbSet<NewsTbl> NewsTbls { get; set; }
    }
}
